version: "3.9"
services:

  frontend:
    image: golosovsa/skypro-pd-cw5-frontend:latest
    ports:
      - 80:80

  backend:
    image: golosovsa/skypro-pd-cw5-backend:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    networks:
      default:
        aliases:
          - api
