version: "3.9"
services:

  frontend:
    image: golosovsa/skypro-pd-cw5-frontend:latest
    ports:
      - 80:80
    volumes:
      - ./frontend_logs:/var/log/nginx

  backend:
    image: golosovsa/skypro-pd-cw5-backend
    build:
      context: .
    networks:
      default:
        aliases:
          - api
