name: testing, building and deploying
on: [ push]
jobs:

  check_pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Copy code
        uses: actions/checkout@v3
      - name: Install python3.11
        run: |
          sudo apt update
          sudo apt install software-properties-common -y
          sudo add-apt-repository ppa:deadsnakes/ppa
          sudo apt update
          sudo apt install python3.11 python3.11-gdbm python3.11-dev python3.11-venv python3.11-tk -y
      - name: Install requirements
        run: pip install -r requirements.pytest.txt
      - name: run pytest
        run: pytest

  check_mypy:
    runs-on: ubuntu-latest
    steps:
      - name: Copy code
        uses: actions/checkout@v3
      - name: Install python3.11
        run: |
          sudo apt update
          sudo apt install software-properties-common -y
          sudo add-apt-repository ppa:deadsnakes/ppa
          sudo apt update
          sudo apt install python3.11 python3.11-gdbm python3.11-dev python3.11-venv python3.11-tk -y
      - name: Install requirements
        run: pip install -r requirements.mypy.txt
      - name: run mypy
        run: mypy wsgi.py

  check_flake8:
    runs-on: ubuntu-latest
    steps:
      - name: Copy code
        uses: actions/checkout@v3
      - name: Install python3.11
        run: |
          sudo apt update
          sudo apt install software-properties-common -y
          sudo add-apt-repository ppa:deadsnakes/ppa
          sudo apt update
          sudo apt install python3.11 python3.11-gdbm python3.11-dev python3.11-venv python3.11-tk -y
      - name: Install requirements
        run: pip install -r requirements.flake8.txt
      - name: run flake8
        run: flake8 .