name: testing, building and deploying
on: [ push]
jobs:

  check_pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Copy code
        uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install requirements
        run: apt install -r requirements.pytest.txt
      - name: run pytest
        run: pytest

  check_mypy:
    runs-on: ubuntu-latest
    steps:
      - name: Copy code
        uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install requirements
        run: apt install -r requirements.mypy.txt
      - name: run mypy
        run: mypy wsgi.py

  check_flake8:
    runs-on: ubuntu-latest
    steps:
      - name: Copy code
        uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install requirements
        run: apt install -r requirements.flake8.txt
      - name: run flake8
        run: flake8 .