name: testing, building and deploying
on: [ push]
jobs:

  check_pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Copy code
        uses: actions/checkout@v3
      - name: Install python3.11
        run: |
          sudo apt update
          sudo apt install software-properties-common -y
          sudo add-apt-repository ppa:deadsnakes/ppa
          sudo apt update
          sudo apt install python3.11 python3.11-gdbm python3.11-dev python3.11-venv python3.11-tk -y
      - name: Install requirements
        run: pip install -r requirements.pytest.txt
      - name: run pytest
        run: pytest .

  check_mypy:
    runs-on: ubuntu-latest
    steps:
      - name: Copy code
        uses: actions/checkout@v3
      - name: Install python3.11
        run: |
          sudo apt update
          sudo apt install software-properties-common -y
          sudo add-apt-repository ppa:deadsnakes/ppa
          sudo apt update
          sudo apt install python3.11 python3.11-gdbm python3.11-dev python3.11-venv python3.11-tk -y
      - name: Install requirements
        run: pip install -r requirements.mypy.txt
      - name: run mypy
        run: mypy .

  check_flake8:
    runs-on: ubuntu-latest
    steps:
      - name: Copy code
        uses: actions/checkout@v3
      - name: Install python3.11
        run: |
          sudo apt update
          sudo apt install software-properties-common -y
          sudo add-apt-repository ppa:deadsnakes/ppa
          sudo apt update
          sudo apt install python3.11 python3.11-gdbm python3.11-dev python3.11-venv python3.11-tk -y
      - name: Install requirements
        run: pip install -r requirements.flake8.txt
      - name: run flake8
        run: flake8 .

  build_and_push_docker:
    runs-on: ubuntu-latest
    needs:
      - check_pytest:
      - check_mypy:
      - check_flake8:
    steps:
      - name: clone code
        uses: actions/checkout@v2
      - name: docker build
        run: docker build -t golosovsa/skypro-pd-cw5-backend:$GITHUB_REF_NAME-$GITHUB_RUN_ID .
      - name: docker login
        run: echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin
      - name: docker push
        run: docker push golosovsa/skypro-pd-cw5-backend:$GITHUB_REF_NAME-$GITHUB_RUN_ID

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push_docker
    steps:
      - name: clone code
        uses: actions/checkout@v2
      - name: render deploy config
        run: |
          mkdir deploy
          cat docker-compose-ci.yaml | envsubst > deploy/docker-compose.yaml
      - name: copy files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          password: ${{ secrets.DEPLOY_PASSWORD }}
          source: "deploy/docker-compose.yaml"
          target: "deploy_ci"
          strip_components: 1
      - name: deploy app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          password: ${{ secrets.DEPLOY_PASSWORD }}
          script: |
      
              cd deploy_ci
              echo '${{ secrets.DEPLOY_PASSWORD }}' | sudo -S docker-compose up -d
